---
# Some general information about this Freifunk community
community: 'bodensee'
community_name: 'Bodensee'
community_shortname: 'ffbsee'

# Some tecnical information like internal IP Adresses
### FYI: We use new addresses on B.A.T.M.A.N. V
ipv6_prefix: 'fdef:1701:b5ee:23:'
ipv4_netz: '10.15.224.0/20'
ipv4_dhcp_server: '10.15.224.6'
ipv4_dhcp_interface: 'bat0'

# some more advanced informations like B.A.T.M.A.N Download Informations
batman_version: '2020.1'
batman_sha256sum: '23abf5576d4594c36a5b6a775f8d2bbd0025f004a8980f68358484f4a0730fbb'
 # https://downloads.open-mesh.org/batman/releases/batman-adv-{{ batman_version }}/batman-adv-{{ batman_version }}.tar.gz
batctl_sha256sum: 'a3e21cbac5f7103925872d80d806d8677f034f8ae8bb6bf6296af81ab028c23b'
 # https://downloads.open-mesh.org/batman/releases/batman-adv-{{ batman_version }}/batctl-{{ batman_version }}.tar.gz
alfred_sha256sum: 'e0721fb40b46c265433cbe6dfcba854e19dad1b69b62475dd01db7af503ea715'
 # https://downloads.open-mesh.org/batman/stable/sources/alfred/alfred-{{ batman_version }}.tar.gz'

fastd_libsodium_version: '1.0.18'
fastd_libsodium_sha256sum: '6f504490b342a4f8a4c4a02fc9b866cbef8622d5df4e5452b46be121e46636c1'
# https://github.com/jedisct1/libsodium/releases/download/{{ fastd_libsodium_version }}/libsodium-{{ fastd_libsodium_version }}.tar.gz
libuecc_url_head: 'https://git.universe-factory.net/libuecc/snapshot/'
libuecc_url_tail: 'libuecc-7.tar'
libuecc_checksum: '0120aee869f56289204255ba81535369816655264dd018c63969bf35b71fd707'
fastd_url_string: 'fastd-18'
fastd_url: 'https://git.universe-factory.net/fastd/snapshot/{{ fastd_url_string }}.tar'
fastd_checksum: 'dce99ee057f43e3d732a120fb0cb60acb3b86e8231d3dd64ab72fc1254c2491a'

# tecnical informations for TLS
letsencrypt_email: 'kommunikation@ffbsee.de'

# make ssh more insecur for legacy rsa keys (mart)
only_allow_ed25519: false

presentation_webserver: 'map.ffbsee.net'
presentation_domain: 'map.ffbsee.net'
