---

- name: Install tinc
  apt:
    pkg: 'tinc'
    state: 'latest'
    update_cache: yes
    cache_valid_time: 86400
  when: run_icvpn == 'true'

- name: Copy tinc nets.boot
  file:
    src: 'files/tinc/nets.boot'
    dest: '/etc/tinc/nets.boot'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Clone current icvpn-scripts from gitthub
  git:
    repo: 'https://github.com/freifunk/icvpn.git'
    dest: '/etc/tinc/icvpn'
    clone: yes
    update: yes

- name: Copy tinc config
  file:
    src: 'files/tinc/tinc.conf'
    dest: '/etc/tinc/icvpn/tinc.conf'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: check if post-merge script exists
  stat: path=/etc/tinc/icvpn/scripts/post-merge
  register: postmerge_stat

- name:  copy post-merge script to .git/hooks
  command: cp /etc/tinc/icvpn/scripts/post-merge /etc/tinc/icvpn/.git/hooks/
  when: postmerge_stat.stat.exists

- name: execute post-merge hook once
  command: /etc/tinc/icvpn/.git/hooks/post-merge

- name: check if tinc private key already exists
  stat: 
  path: /etc/tinc/icvpn/rsa_key.priv
  register: privkey_exists  

- name: create public/private key pair for tinc
  shell: yes | tincd -n icvpn -K
  when: privkey_exists.stat.exists == False
